account_prefix: dev
cicdpipeline_branch: dev
tl_developer_role: 
vpc_stack: 
code_commit_branches: dev
snowflake_account: 
snowflake_warehouse: 
snowflake_metadata_database: 
snowflake_metadata_schema: 
