account_prefix: prod
cicdpipeline_branch: prod
tl_developer_role: 
vpc_stack: 
code_commit_branches: prod
snowflake_account: 
snowflake_warehouse: 
snowflake_metadata_database: 
snowflake_metadata_schema: 
